os:
    - linux

language: python
python:
    - "3.6"

install:
    - pip install coveralls
    - pip install -r requirements.txt
    - mkdir -p /tmp/deployment

script:
    - coverage run  --source server_lib  -m unittest discover tests

after_success:
    coveralls
